### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by agursoy** [claudivanfilho/v-slim-mask#1]
Hi, thank for great library. Your library works great. But placeholder will not be showed. I want to initial input with example value. 

`<input v-mask="{mask: '### ### ## ##'}" required id="subscriber_phone" placeholder="532 123 52 23" type="tel">`

but it shows empty input 

<img width="282" alt="Screen Shot 2021-08-23 at 17 24 46" src="https://user-images.githubusercontent.com/1447418/130464295-e546a341-6a9e-45df-a603-3572b60ec07a.png">

**Comment by claudivanfilho** [comment]
Hi @agursoy tks for the report i will take a look soon

**Comment by agursoy** [comment]
Sorry for take your time. It worked after use v-model.

**Comment by claudivanfilho** [comment]
Solved
